### ISSUE TITLE
If the error is related to alexflipnote api, well that api is no longer provided, if that's not the case then what's wrong here?

### ISSUE THREAD

**Issue by hallalujeh** [Dev-CasperTheGhost/GhostyBot#350]
> ghostybot@2.0.0 start
> cross-env DEV_MODE=false node -r ts-node/register -r tsconfig-paths/register ./dist/index.js
[WARNING][ENV_OPTIONS][13.02.2022, 20:26:00]: env option: "ALEXFLIPNOTE_API_KEY" was not provided in a .env file. This may be required for some commands.
/workspace/node_modules/mongoose/lib/cursor/QueryCursor.js:144
QueryCursor.prototype.map = function(fn) {
^
TypeError: Cannot assign to read only property 'map' of object '#<QueryCursor>'
at Object.<anonymous> (/workspace/node_modules/mongoose/lib/cursor/QueryCursor.js:144:27)
at Module._compile (node:internal/modules/cjs/loader:1097:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1151:10)
at Object.require.extensions.<computed> [as .js] (/workspace/node_modules/ts-node/src/index.ts:1361:43)
at Module.load (node:internal/modules/cjs/loader:975:32)
at Function.Module._load (node:internal/modules/cjs/loader:822:12)
at Module.require (node:internal/modules/cjs/loader:999:19)
at require (node:internal/modules/cjs/helpers:102:18)
at Object.<anonymous> (/workspace/node_modules/mongoose/lib/query.js:12:21)
at Module._compile (node:internal/modules/cjs/loader:1097:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1151:10)
at Object.require.extensions.<computed> [as .js] (/workspace/node_modules/ts-node/src/index.ts:1361:43)
at Module.load (node:internal/modules/cjs/loader:975:32)
at Function.Module._load (node:internal/modules/cjs/loader:822:12)
at Module.require (node:internal/modules/cjs/loader:999:19)
at require (node:internal/modules/cjs/helpers:102:18)

**Comment by Xaliks** [comment]
https://stackoverflow.com/questions/71073107/does-anyone-know-nay-fix-for-this-error-typeerror-cannot-assign-to-read-only-p/71073989
![Screenshot_20220214-003335_Chrome Canary](https://user-images.githubusercontent.com/64866197/153776055-ccec7c3d-97fe-4b3d-b827-31291886883f.jpg)
